---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: votingapp
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/shubhanjan-banerjee/arch-neo-2023-group-2-e-commerce-application
